#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract HTML from camera_index.h and compress to gzip format
从camera_index.h提取HTML并压缩为gzip格式
"""

import gzip
import os

# 读取camera_index.h中的HTML内容
with open('camera_index.h', 'r', encoding='utf-8') as f:
    content = f.read()

# 提取HTML内容（在R"rawliteral(和)rawliteral"之间）
start = content.find('R"rawliteral(') + len('R"rawliteral(')
end = content.find(')rawliteral"')
html_content = content[start:end]

print(f'HTML content extracted: {len(html_content)} characters')

# 保存为临时HTML文件
with open('temp_index.html', 'w', encoding='utf-8') as f:
    f.write(html_content)
print(f'Saved to: temp_index.html')

# Gzip压缩
html_bytes = html_content.encode('utf-8')
compressed = gzip.compress(html_bytes, compresslevel=9)

print(f'\nOriginal size: {len(html_bytes)} bytes')
print(f'Compressed size: {len(compressed)} bytes')
print(f'Compression ratio: {(1 - len(compressed)/len(html_bytes))*100:.1f}%')

# 生成C头文件
var_name = "index_ov2640_html_gz"
header_content = f"""/*
 * Compressed HTML file / 压缩的HTML文件
 * Original file / 原始文件: camera_index.h
 * Original size / 原始大小: {len(html_bytes)} bytes
 * Compressed size / 压缩大小: {len(compressed)} bytes
 * Compression ratio / 压缩率: {(1 - len(compressed)/len(html_bytes))*100:.1f}%
 * Generated at / 生成时间: 2026-01-30
 * 
 * 注意 / Note: 此文件由工具自动生成，请勿手动修改
 *       This file is auto-generated by tool, do not modify manually
 */

#define {var_name.upper()}_LEN {len(compressed)}
const uint8_t {var_name}[] = {{
"""

# 将压缩数据格式化为C数组
bytes_per_line = 16
for i in range(0, len(compressed), bytes_per_line):
    line = compressed[i:i+bytes_per_line]
    hex_values = ', '.join(f'0x{b:02X}' for b in line)
    header_content += f" {hex_values},\n"

# 移除最后一个逗号
header_content = header_content.rstrip(',\n') + "\n"

header_content += """};
"""

# 写入输出文件
with open('camera_index_compressed.h', 'w', encoding='utf-8') as f:
    f.write(header_content)

print(f'\nCompressed header file generated: camera_index_compressed.h')
print(f'Variable name: {var_name}')
print(f'Size constant: {var_name.upper()}_LEN')
